### ISSUE TITLE
segmentation violation when using consumeMessageCurrently

### ISSUE THREAD

**Issue by qshuai** [apache/rocketmq-client-go#1028]
rocketmq-client version: v2.1.0

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xf5f0c7]

goroutine 1959 [running]:
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End·dwrap·12()
	/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.7.0/trace/span.go:359 +0x2a
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End(0xc002bb6300, {0x0, 0x0, 0x0})
	/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.7.0/trace/span.go:398 +0x9a2
panic({0x10a9740, 0x1cfe550})
	/usr/local/go/src/runtime/panic.go:1047 +0x266
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End·dwrap·12()
	/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.7.0/trace/span.go:359 +0x2a
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End(0xc002bb6480, {0x0, 0x0, 0x0})
	/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.7.0/trace/span.go:398 +0x9a2
panic({0x10a9740, 0x1cfe550})
	/usr/local/go/src/runtime/panic.go:1047 +0x266
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End·dwrap·12()
	/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.7.0/trace/span.go:359 +0x2a
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End(0xc002bb7080, {0x0, 0x0, 0x0})
	/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.7.0/trace/span.go:398 +0x9a2
panic({0x10a9740, 0x1cfe550})
	/usr/local/go/src/runtime/panic.go:1047 +0x266
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End·dwrap·12()
	/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.7.0/trace/span.go:359 +0x2a
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End(0xc002bb7200, {0x0, 0x0, 0x0})
	/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.7.0/trace/span.go:398 +0x9a2
panic({0x10a9740, 0x1cfe550})
	/usr/local/go/src/runtime/panic.go:1047 +0x266
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End·dwrap·12()
	/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.7.0/trace/span.go:359 +0x2a
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End(0xc002bb7380, {0x0, 0x0, 0x0})
	/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.7.0/trace/span.go:398 +0x9a2
panic({0x10a9740, 0x1cfe550})
	/usr/local/go/src/runtime/panic.go:1047 +0x266
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End·dwrap·12()
	/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.7.0/trace/span.go:359 +0x2a
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End(0xc002bb7500, {0x0, 0x0, 0x0})
	/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.7.0/trace/span.go:398 +0x9a2
panic({0x10a9740, 0x1cfe550})
	/usr/local/go/src/runtime/panic.go:1047 +0x266
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End·dwrap·12()
	/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.7.0/trace/span.go:359 +0x2a
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End(0xc002bb7680, {0x0, 0x0, 0x0})
	/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.7.0/trace/span.go:398 +0x9a2
panic({0x10a9740, 0x1cfe550})
	/usr/local/go/src/runtime/panic.go:1047 +0x266
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End·dwrap·12()
	/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.7.0/trace/span.go:359 +0x2a
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End(0xc002bb7800, {0x0, 0x0, 0x0})
	/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.7.0/trace/span.go:398 +0x9a2
panic({0x10a9740, 0x1cfe550})
	/usr/local/go/src/runtime/panic.go:1047 +0x266
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End·dwrap·12()
	/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.7.0/trace/span.go:359 +0x2a
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End(0xc002bb7980, {0x0, 0x0, 0x0})
	/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.7.0/trace/span.go:398 +0x9a2
panic({0x10a9740, 0x1cfe550})
	/usr/local/go/src/runtime/panic.go:1047 +0x266
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End·dwrap·12()
	/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.7.0/trace/span.go:359 +0x2a
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End(0xc002bb7b00, {0x0, 0x0, 0x0})
	/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.7.0/trace/span.go:398 +0x9a2
panic({0x10a9740, 0x1cfe550})
	/usr/local/go/src/runtime/panic.go:1047 +0x266
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End·dwrap·12()
	/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.7.0/trace/span.go:359 +0x2a
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End(0xc002bb7c80, {0x0, 0x0, 0x0})
	/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.7.0/trace/span.go:398 +0x9a2
panic({0x10a9740, 0x1cfe550})
	/usr/local/go/src/runtime/panic.go:1047 +0x266
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End·dwrap·12()
	/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.7.0/trace/span.go:359 +0x2a
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End(0xc002bb7e00, {0x0, 0x0, 0x0})
	/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.7.0/trace/span.go:398 +0x9a2
panic({0x10a9740, 0x1cfe550})
	/usr/local/go/src/runtime/panic.go:1047 +0x266
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End·dwrap·12()
	/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.7.0/trace/span.go:359 +0x2a
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End(0xc0026ee780, {0x0, 0x0, 0x0})
	/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.7.0/trace/span.go:398 +0x9a2
panic({0x10a9740, 0x1cfe550})
	/usr/local/go/src/runtime/panic.go:1047 +0x266
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End·dwrap·12()
	/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.7.0/trace/span.go:359 +0x2a
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End(0xc0026ee900, {0x0, 0x0, 0x0})
	/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.7.0/trace/span.go:398 +0x9a2
panic({0x10a9740, 0x1cfe550})
	/usr/local/go/src/runtime/panic.go:1047 +0x266
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End·dwrap·12()
	/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.7.0/trace/span.go:359 +0x2a
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End(0xc0026eea80, {0x0, 0x0, 0x0})
	/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.7.0/trace/span.go:398 +0x9a2
panic({0x10a9740, 0x1cfe550})
	/usr/local/go/src/runtime/panic.go:1047 +0x266
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End·dwrap·12()
	/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.7.0/trace/span.go:359 +0x2a
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End(0xc0026eec00, {0x0, 0x0, 0x0})
	/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.7.0/trace/span.go:398 +0x9a2
panic({0x10a9740, 0x1cfe550})
	/usr/local/go/src/runtime/panic.go:1047 +0x266
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End·dwrap·12()
	/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.7.0/trace/span.go:359 +0x2a
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End(0xc0026eed80, {0x0, 0x0, 0x0})
	/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.7.0/trace/span.go:398 +0x9a2
panic({0x10a9740, 0x1cfe550})
	/usr/local/go/src/runtime/panic.go:1047 +0x266
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End·dwrap·12()
	/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.7.0/trace/span.go:359 +0x2a
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End(0xc0026eef00, {0x0, 0x0, 0x0})
	/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.7.0/trace/span.go:398 +0x9a2
panic({0x10a9740, 0x1cfe550})
	/usr/local/go/src/runtime/panic.go:1047 +0x266
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End·dwrap·12()
	/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.7.0/trace/span.go:359 +0x2a
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End(0xc0026ef080, {0x0, 0x0, 0x0})
	/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.7.0/trace/span.go:398 +0x9a2
panic({0x10a9740, 0x1cfe550})
	/usr/local/go/src/runtime/panic.go:1047 +0x266
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End·dwrap·12()
	/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.7.0/trace/span.go:359 +0x2a
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End(0xc0026ef200, {0x0, 0x0, 0x0})
	/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.7.0/trace/span.go:398 +0x9a2
panic({0x10a9740, 0x1cfe550})
	/usr/local/go/src/runtime/panic.go:1047 +0x266
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End·dwrap·12()
	/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.7.0/trace/span.go:359 +0x2a
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End(0xc0026ef380, {0x0, 0x0, 0x0})
	/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.7.0/trace/span.go:398 +0x9a2
panic({0x10a9740, 0x1cfe550})
	/usr/local/go/src/runtime/panic.go:1047 +0x266
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End·dwrap·12()
	/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.7.0/trace/span.go:359 +0x2a
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End(0xc0026ef500, {0x0, 0x0, 0x0})
	/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.7.0/trace/span.go:398 +0x9a2
panic({0x10a9740, 0x1cfe550})
	/usr/local/go/src/runtime/panic.go:1047 +0x266
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End·dwrap·12()
	/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.7.0/trace/span.go:359 +0x2a
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End(0xc0026ef680, {0x0, 0x0, 0x0})
	/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.7.0/trace/span.go:398 +0x9a2
panic({0x10a9740, 0x1cfe550})
	/usr/local/go/src/runtime/panic.go:1047 +0x266
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End·dwrap·12()
	/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.7.0/trace/span.go:359 +0x2a
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End(0xc0026ef800, {0x0, 0x0, 0x0})
	/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.7.0/trace/span.go:398 +0x9a2
panic({0x10a9740, 0x1cfe550})
	/usr/local/go/src/runtime/panic.go:1047 +0x266
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End·dwrap·12()
	/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.7.0/trace/span.go:359 +0x2a
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End(0xc0026ef980, {0x0, 0x0, 0x0})
	/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.7.0/trace/span.go:398 +0x9a2
created by github.com/apache/rocketmq-client-go/v2/consumer.(*pushConsumer).consumeMessageCurrently
	/go/pkg/mod/github.com/apache/rocketmq-client-go/v2@v2.1.0/consumer/push_consumer.go:969 +0x85
```

**Comment by francisoliverlee** [comment]
can you show you codes ?
