### ISSUE TITLE
consumer examples run error

### ISSUE THREAD

**Issue by pangliang** [apache/rocketmq-client-go#144]
* native branch
* run   github.com/apache/rocketmq-client-go/examples/consumer/simple/main.go

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x57da28]

goroutine 86 [running]:
github.com/apache/rocketmq-client-go/internal/utils.MakeFileIfNotExist(0xc0001f8000, 0x42, 0x0, 0x0)
	/home/wei.liang/go/src/github.com/apache/rocketmq-client-go/internal/utils/files.go:54 +0x168
github.com/apache/rocketmq-client-go/internal/utils.WriteToFile(0xc0001f8000, 0x4e, 0xc000020b98, 0x2, 0x8, 0x0, 0x0)
	/home/wei.liang/go/src/github.com/apache/rocketmq-client-go/internal/utils/files.go:61 +0x83
github.com/apache/rocketmq-client-go/consumer.(*localFileOffsetStore).persist(0xc0001ee0c0, 0xc0000100b0, 0x1, 0x1)
	/home/wei.liang/go/src/github.com/apache/rocketmq-client-go/consumer/offset_store.go:173 +0x546
github.com/apache/rocketmq-client-go/consumer.(*defaultConsumer).persistConsumerOffset(0xc0000af180, 0x0, 0x0)
	/home/wei.liang/go/src/github.com/apache/rocketmq-client-go/consumer/consumer.go:311 +0x129
github.com/apache/rocketmq-client-go/consumer.(*pushConsumer).PersistConsumerOffset(0xc000120640, 0x0, 0x0)
	/home/wei.liang/go/src/github.com/apache/rocketmq-client-go/consumer/push_consumer.go:190 +0x3d
github.com/apache/rocketmq-client-go/internal.(*rmqClient).Start.func1.4.1(0x6201a0, 0xc0001dc0a0, 0x6649a0, 0xc000120640, 0x40dc00)
	/home/wei.liang/go/src/github.com/apache/rocketmq-client-go/internal/client.go:220 +0x9d
sync.(*Map).Range(0xc0001f40e0, 0x672b68)
	/server/go/src/sync/map.go:333 +0x3d7
github.com/apache/rocketmq-client-go/internal.(*rmqClient).Start.func1.4(0xc0001f4000)
	/home/wei.liang/go/src/github.com/apache/rocketmq-client-go/internal/client.go:218 +0x58
created by github.com/apache/rocketmq-client-go/internal.(*rmqClient).Start.func1
	/home/wei.liang/go/src/github.com/apache/rocketmq-client-go/internal/client.go:215 +0x124
```

**Comment by wenfengwang** [comment]
fixed at https://github.com/apache/rocketmq-client-go/pull/145
