### ISSUE TITLE
[Master]Shutdown producer error

### ISSUE THREAD

**Issue by luthfikw** [apache/rocketmq-client-go#329]
Branch **master**

1. Please describe the issue you observed:

    - What did you do (The steps to reproduce)?
       first i run golang to produce message orderly
       then defer Shutdown() to shutdown the producer client

    - What did you expect to see?
       no panic thown

    - What did you see instead?
      i got error

```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x428ea25]

      runtime stack:
runtime.throw(0x40f99b8, 0x2a)
	/Users/gearintellix/.gvm/gos/go1.12.9/src/runtime/panic.go:617 +0x72
runtime.sigpanic()
	/Users/gearintellix/.gvm/gos/go1.12.9/src/runtime/signal_unix.go:374 +0x4a9

goroutine 1 [syscall]:
runtime.cgocall(0x40b5630, 0xc000048dd0, 0xc000000000)
	/Users/gearintellix/.gvm/gos/go1.12.9/src/runtime/cgocall.go:128 +0x5b fp=0xc000048da0 sp=0xc000048d68 pc=0x4004bbb
github.com/apache/rocketmq-client-go/core._Cfunc_DestroyProducer(0x4700000, 0x0)
	_cgo_gotypes.go:286 +0x49 fp=0xc000048dd0 sp=0xc000048da0 pc=0x40ab689
github.com/apache/rocketmq-client-go/core.(*defaultProducer).Shutdown.func2(0xc000012130, 0xc000000000)
	/Users/gearintellix/Sites/go/src/github.com/apache/rocketmq-client-go/core/producer.go:212 +0x5f fp=0xc000048e10 sp=0xc000048dd0 pc=0x40b25df
github.com/apache/rocketmq-client-go/core.(*defaultProducer).Shutdown(0xc000012130, 0x0, 0x41c8260)
	/Users/gearintellix/Sites/go/src/github.com/apache/rocketmq-client-go/core/producer.go:212 +0x47 fp=0xc000048e30 sp=0xc000048e10 pc=0x40af367
main.sendMessage(0xc0000ae000)
	/Users/gearintellix/Sites/goext/tester/rocketmq-client-go/examples/producer.go:63 +0x4cd fp=0xc000048f78 sp=0xc000048e30 pc=0x40b4b6d
main.main()
	/Users/gearintellix/Sites/goext/tester/rocketmq-client-go/examples/producer.go:35 +0x7e fp=0xc000048f98 sp=0xc000048f78 pc=0x40b465e
runtime.main()
	/Users/gearintellix/.gvm/gos/go1.12.9/src/runtime/proc.go:200 +0x20c fp=0xc000048fe0 sp=0xc000048f98 pc=0x402cd6c
runtime.goexit()
	/Users/gearintellix/.gvm/gos/go1.12.9/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000048fe8 sp=0xc000048fe0 pc=0x4054761
exit status 2
```

2. Please tell us about your environment:

     - What is your OS?
        MacOS Mojave

     - What is your client version?
        Lastest master (10 Dec 2019)

     - What is your RocketMQ version?
        V4_6_0

**Comment by ShannonDing** [comment]
This is a timing bug. it also happens when the consumer is shutdown.
Two C methods are called in the shutdown function:
1. shutdown instance;
2. destroy instance;
the C shutdown method is asynchronous，so the memory of this instance may be released before its shutdown process finished.

**Comment by luthfikw** [comment]
oh i see, thanks you

**Comment by wenfengwang** [comment]
close due to resloved

**Comment by ShannonDing** [comment]
link apache/rocketmq-client-cpp#212

**Comment by codeMingo** [comment]
this error Resolved? I got error

**Comment by ShannonDing** [comment]
what 's the CPP core version in your env?
