### ISSUE TITLE
v2.0.0 fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by feiquan123** [apache/rocketmq-client-go#544]
5 个 mqClient 初始化如下：
```
consumer1, _ := rocketmq.NewPushConsumer(
		consumer.WithGroupName(v.GetString("rocketMQ.consumerGroup1")),
		consumer.WithNameServer(nameServer),
		consumer.WithConsumerModel(consumer.BroadCasting),
		consumer.WithConsumeFromWhere(consumer.ConsumeFromLastOffset),
		consumer.WithPullBatchSize(100),
		consumer.WithPullInterval(1000),
	)
consumer2, _ := rocketmq.NewPushConsumer(
		consumer.WithGroupName(v.GetString("rocketMQ.consumerGroup2")),
		consumer.WithNameServer(nameServer),
		consumer.WithConsumerModel(consumer.BroadCasting),
		consumer.WithConsumeFromWhere(consumer.ConsumeFromLastOffset),
		consumer.WithPullBatchSize(100),
		consumer.WithPullInterval(1000),
	)
...
consumer5, _ := rocketmq.NewPushConsumer(
		consumer.WithGroupName(v.GetString("rocketMQ.consumerGroup5")),
		consumer.WithNameServer(nameServer),
		consumer.WithConsumerModel(consumer.BroadCasting),
		consumer.WithConsumeFromWhere(consumer.ConsumeFromLastOffset),
		consumer.WithPullBatchSize(100),
		consumer.WithPullInterval(1000),
	)
```

报错如下：
```
time="2020-10-30T21:05:53+08:00" level=info msg="receive get consumer running info request..."
time="2020-10-30T21:05:57+08:00" level=info msg="receive get consumer running info request..."
fatal error: concurrent map read and map write

goroutine 3218015 [running]:
runtime.throw(0x1217fd3, 0x21)
	/usr/lib/go/src/runtime/panic.go:774 +0x72 fp=0xc14761ba40 sp=0xc14761ba10 pc=0x42f5b2
runtime.mapaccess2(0x1018480, 0xc1255f33b0, 0xc14761bab0, 0x0, 0x175799d5d29)
	/usr/lib/go/src/runtime/map.go:470 +0x278 fp=0xc14761ba88 sp=0xc14761ba40 pc=0x40e0b8
github.com/apache/rocketmq-client-go/v2/consumer.readFromMemory(...)
	/go/pkg/mod/github.com/apache/rocketmq-client-go/v2@v2.0.0/consumer/offset_store.go:381
github.com/apache/rocketmq-client-go/v2/consumer.(*localFileOffsetStore).read(0xc1255f33e0, 0xc14f2ffa40, 0x2, 0x0)
	/go/pkg/mod/github.com/apache/rocketmq-client-go/v2@v2.0.0/consumer/offset_store.go:161 +0x78 fp=0xc14761bae8 sp=0xc14761ba88 pc=0xd7e528
github.com/apache/rocketmq-client-go/v2/consumer.(*pushConsumer).GetConsumerRunningInfo.func2(0x10d7160, 0xc127eabbf0, 0x11be480, 0xc127b17500, 0x111f801)
	/go/pkg/mod/github.com/apache/rocketmq-client-go/v2@v2.0.0/consumer/push_consumer.go:292 +0x17a fp=0xc14761bc20 sp=0xc14761bae8 pc=0xd911ba
sync.(*Map).Range(0xc122e9cb18, 0xc14761bda8)
	/usr/lib/go/src/sync/map.go:333 +0x1c3 fp=0xc14761bcf8 sp=0xc14761bc20 pc=0x47c133
github.com/apache/rocketmq-client-go/v2/consumer.(*pushConsumer).GetConsumerRunningInfo(0xc121d9db60, 0x11e6fe0)
	/go/pkg/mod/github.com/apache/rocketmq-client-go/v2@v2.0.0/consumer/push_consumer.go:288 +0x18f fp=0xc14761bde8 sp=0xc14761bcf8 pc=0xd839df
github.com/apache/rocketmq-client-go/v2/internal.(*rmqClient).getConsumerRunningInfo(0xc00bebfba0, 0xc141b7d800, 0x20, 0x0)
	/go/pkg/mod/github.com/apache/rocketmq-client-go/v2@v2.0.0/internal/client.go:741 +0xa4 fp=0xc14761be40 sp=0xc14761bde8 pc=0xd64524
github.com/apache/rocketmq-client-go/v2/internal.GetOrNewRocketMQClient.func3(0xc14f04ab40, 0x13adec0, 0xc127912360, 0x44e0a7)
/go/pkg/mod/github.com/apache/rocketmq-client-go/v2@v2.0.0/internal/client.go:236 +0x303 fp=0xc14761bf00 sp=0xc14761be40 pc=0xd6e473
github.com/apache/rocketmq-client-go/v2/internal/remote.(*remotingClient).processCMD.func2()
	/go/pkg/mod/github.com/apache/rocketmq-client-go/v2@v2.0.0/internal/remote/remote_client.go:207 +0x69 fp=0xc14761bf88 sp=0xc14761bf00 pc=0xd60d29
github.com/apache/rocketmq-client-go/v2/primitive.WithRecover(0xc14f0fdce0)
	/go/pkg/mod/github.com/apache/rocketmq-client-go/v2@v2.0.0/primitive/base.go:96 +0x4d fp=0xc14761bfd8 sp=0xc14761bf88 pc=0xd5617d
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc14761bfe0 sp=0xc14761bfd8 pc=0x45f851
created by github.com/apache/rocketmq-client-go/v2/internal/remote.(*remotingClient).processCMD
	/go/pkg/mod/github.com/apache/rocketmq-client-go/v2@v2.0.0/internal/remote/remote_client.go:206 +0x1f1
```

**Comment by feiquan123** [comment]
```go
type localFileOffsetStore struct {
	group       string
	path        string
	OffsetTable map[MessageQueueKey]int64  // replace sync.Map
	// mutex for offset file
	mutex sync.Mutex
}
```
