### ISSUE TITLE
[Master] Support consume message directly

### ISSUE THREAD

**Issue by maixiaohai** [apache/rocketmq-client-go#621]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.
**Support consume message directly**
2. Provide any additional detail on your proposed use case for this feature.
stack from console
```
resent message to xxxx@c9eec7fc4734025f fail
org.apache.rocketmq.client.exception.MQClientException: CODE: 207  DESC: consumer <Notify_Channel_761_1217> <xxxx@c9eec7fc4734025f> Timeout: org.apache.rocketmq.remoting.exception.RemotingTimeoutException: wait response on the channel <xxxx> timeout, 10000(ms), org.apache.rocketmq.remoting.netty.NettyRemotingAbstract.invokeSyncImpl(NettyRemotingAbstract.java:438)
For more information, please visit the url, http://rocketmq.apache.org/docs/faq/
        at org.apache.rocketmq.client.impl.MQClientAPIImpl.consumeMessageDirectly(MQClientAPIImpl.java:1898)
        at org.apache.rocketmq.tools.admin.DefaultMQAdminExtImpl.consumeMessageDirectly(DefaultMQAdminExtImpl.java:772)
        at org.apache.rocketmq.tools.admin.DefaultMQAdminExt.consumeMessageDirectly(DefaultMQAdminExt.java:434)
```
2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

**Comment by ShannonDing** [comment]
close due to #662
