### ISSUE TITLE
[Master] producer.SendAsync() panic bug

### ISSUE THREAD

**Issue by iGoogle-ink** [apache/rocketmq-client-go#655]
The issue tracker is **ONLY** used for the go client (feature request of RocketMQ need to follow [RIP process](https://github.com/apache/rocketmq/wiki/RocketMQ-Improvement-Proposal)). Keep in mind, please check whether there is an existing same report before your raise a new one.

Alternately (especially if your communication is not a bug report), you can send mail to our [mailing lists](http://rocketmq.apache.org/about/contact/). We welcome any friendly suggestions, bug fixes, collaboration, and other improvements.

Please ensure that your bug report is clear and that it is complete. Otherwise, we may be unable to understand it or to reproduce it, either of which would prevent us from fixing the bug. We strongly recommend the report(bug report or feature request) could include some hints as to the following:

**BUG REPORT**  
**Please add the branch name [Native]/[Master] at the header of the Isssue title.**

1. Please describe the issue you observed:

    - What did you do (The steps to reproduce)?
    
when i call producer.SendAsync() method ,input mq parameter nil, you are not judgment if function parameter is nil.

    - What did you expect to see?
not panic
    - What did you see instead?

2. Please tell us about your environment:

     - What is your OS? mac os

     - What is your client version?  v2.1.0

     - What is your RocketMQ version? 

3. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):

`panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1370a4f]

goroutine 58 [running]:
github.com/apache/rocketmq-client-go/v2/producer.(*defaultProducer).sendAsync.func1(0xc000153440, 0x0, 0x0)
	/Users/jerry/workspace/gopath/pkg/mod/github.com/apache/rocketmq-client-go/v2@v2.1.0/producer/producer.go:253 +0x16f
github.com/apache/rocketmq-client-go/v2/internal.(*rmqClient).InvokeAsync.func1(0xc000020500)
	/Users/jerry/workspace/gopath/pkg/mod/github.com/apache/rocketmq-client-go/v2@v2.1.0/internal/client.go:461 +0x44
github.com/apache/rocketmq-client-go/v2/internal/remote.(*ResponseFuture).executeInvokeCallback.func1()
	/Users/jerry/workspace/gopath/pkg/mod/github.com/apache/rocketmq-client-go/v2@v2.1.0/internal/remote/future.go:51 +0x3d
sync.(*Once).doSlow(0xc000020530, 0xc0001b9f78)
	/usr/local/go/src/sync/once.go:68 +0xec
sync.(*Once).Do(...)
	/usr/local/go/src/sync/once.go:59
github.com/apache/rocketmq-client-go/v2/internal/remote.(*ResponseFuture).executeInvokeCallback(0xc000020500)
	/Users/jerry/workspace/gopath/pkg/mod/github.com/apache/rocketmq-client-go/v2@v2.1.0/internal/remote/future.go:49 +0x65
github.com/apache/rocketmq-client-go/v2/internal/remote.(*remotingClient).processCMD.func1()
	/Users/jerry/workspace/gopath/pkg/mod/github.com/apache/rocketmq-client-go/v2@v2.1.0/internal/remote/remote_client.go:195 +0x45
github.com/apache/rocketmq-client-go/v2/primitive.WithRecover(0xc00013e978)
	/Users/jerry/workspace/gopath/pkg/mod/github.com/apache/rocketmq-client-go/v2@v2.1.0/primitive/base.go:96 +0x49
created by github.com/apache/rocketmq-client-go/v2/internal/remote.(*remotingClient).processCMD
	/Users/jerry/workspace/gopath/pkg/mod/github.com/apache/rocketmq-client-go/v2@v2.1.0/internal/remote/remote_client.go:193 +0x12c`

![image](https://user-images.githubusercontent.com/17245594/117466064-e821b880-af84-11eb-88fe-940539e9cf34.png)

**Comment by maixiaohai** [comment]
IMO, the nil check for the func should be added in the logic of user code. It's the callback of async send, seems necessary.

**Comment by maixiaohai** [comment]
> if user don't care callback ,they can input nil

SendOneWay() is a better choice for this case.
