### ISSUE TITLE
panic: runtime error: index out of range [-1]

### ISSUE THREAD

**Issue by hxnan** [apache/rocketmq-client-go#815]
```
panic: runtime error: index out of range [-1]

goroutine 359187 [running]:
math/rand.(*rngSource).Uint64(0xc000452000)  
        D:/Go/src/math/rand/rng.go:250 +0x148
math/rand.(*rngSource).Int63(0xc000452000)   
        D:/Go/src/math/rand/rng.go:234 +0x2c 
math/rand.(*Rand).Int63(0xc0004382a0)        
        D:/Go/src/math/rand/rand.go:84 +0x38
math/rand.(*Rand).Int31(0xc0004382a0)
        D:/Go/src/math/rand/rand.go:98 +0x2b
math/rand.(*Rand).Int31n(0xc0004382a0, 0x8)
        D:/Go/src/math/rand/rand.go:130 +0x50
math/rand.(*Rand).Intn(0xc0004382a0, 0x8)
        D:/Go/src/math/rand/rand.go:171 +0x53
github.com/apache/rocketmq-client-go/v2/producer.randomQueueSelector.Select({0xc0004382a0}, 0xc000413b20, {0xc00020c8c0, 0x8, 0x8})
        D:/git/router-go/vendor/github.com/apache/rocketmq-client-go/v2/producer/selector.go:57 +0x4e
github.com/apache/rocketmq-client-go/v2/producer.(*hashQueueSelector).Select(0xc0003b8fc0, 0xc000413b20, {0xc00020c8c0, 0x8, 0x8})
        D:/git/router-go/vendor/github.com/apache/rocketmq-client-go/v2/producer/selector.go:110 +0xb5
github.com/apache/rocketmq-client-go/v2/producer.(*defaultProducer).selectMessageQueue(0xc000384ea0, 0xc000413b20)
        D:/git/router-go/vendor/github.com/apache/rocketmq-client-go/v2/producer/producer.go:396 +0x557
github.com/apache/rocketmq-client-go/v2/producer.(*defaultProducer).sendSync(0xc000384ea0, {0x1226ae8, 0xc0000360e8}, 0xc000413b20, 0xc000234480)
        D:/git/router-go/vendor/github.com/apache/rocketmq-client-go/v2/producer/producer.go:188 +0x168
github.com/apache/rocketmq-client-go/v2/producer.(*defaultProducer).SendSync(0xc000384ea0, {0x1226ae8, 0xc0000360e8}, {0xc0004ac0a8, 0x1, 0x1})
        D:/git/router-go/vendor/github.com/apache/rocketmq-client-go/v2/producer/producer.go:170 +0x41b

```

**Comment by hxnan** [comment]
I got a issue like this:

https://github.com/golang/go/issues/17629

**Comment by ShannonDing** [comment]
close first. it will be reopen on this issue  occur again.
